config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :things
  resources :users
  
  namespace :api do 
    namespace :v1 do 
     resources :things
     post 'image_search', to: 'model_versions#image_search'
     get 'model_versions/latest', to: 'model_versions#latest'
     post 'model_versions/:id/image_search', to: 'model_versions#image_search'
     post 'model_versions/:id/things', to: 'model_versions#things'
     get 'model_versions/:id/:filepath', constraints: { filepath: /.*/ }, to: 'model_versions#show'
    end 
  end 

  get 'things/:id', to: 'things#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/thing.rb
class Thing < ApplicationRecord
  include Searchable
  index_name    "things"

  belongs_to :job, optional: true
  belongs_to :user

  has_many :tag_things
  has_many :tags, through: :tag_things

  has_many :category_things
  has_many :categories, through: :category_things

  has_many :thing_files

  has_many :model_version_images


  def as_indexed_json(options={})
    self.as_json(
      include: { categories: { only: :name},
                 tags:    { methods: [:lname], only: [:lname, :thing_count] },
                 thing_files:   { only: [:name, :download_count] },
                 user: { only: [:name, :first_name, :last_name]}
               })
  end

  def self.indexme
    self.__elasticsearch__.create_index! force: true
  end
end

app/controllers/api/v1/things_controller.rb
class Api::V1::ThingsController < ApplicationController
  before_action :set_thing, only: [:show, :edit, :update, :destroy]

  # GET /things
  # GET /things.json
  def index
    per_page = [params.fetch("per_page", 20).to_i, 50].min
    page = params.fetch("page", 1)
    things = 
      if params[:q].blank?
        Thing.includes(:categories, :tags, :user).where(deleted: false).order("id desc").
          page(page).per(per_page).collect do |t|
            {"id": t["id"], "attributes": t.as_json(
              include: { categories: { only: :name},
                       tags:    { methods: [:lname], only: [:lname, :thing_count] },
                       user: { only: [:name, :first_name, :last_name]}
                      })
            }
          end
      else
        Thing.search(params[:q]).page(page).per(per_page).collect do |t|
          {"id": t["_source"]["id"], "attributes": t["_source"] }
        end
      end

    render json: {data: things, meta: {page: page, per_page: per_page}}

  end

  # GET /things/1
  # GET /things/1.json
  def show
  end

  # GET /things/new
  def new
    @thing = Thing.new
  end

  # GET /things/1/edit
  def edit
  end

  # POST /things
  # POST /things.json
  def create
    # @thing = Thing.new(thing_params)

    # respond_to do |format|
    #   if @thing.save
    #     format.html { redirect_to @thing, notice: 'Thing was successfully created.' }
    #     format.json { render :show, status: :created, location: @thing }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @thing.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /things/1
  # PATCH/PUT /things/1.json
  def update
    # respond_to do |format|
    #   if @thing.update(thing_params)
    #     format.html { redirect_to @thing, notice: 'Thing was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @thing }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @thing.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    # @thing.destroy
    # respond_to do |format|
    #   format.html { redirect_to things_url, notice: 'Thing was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @thing = Thing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thing_params
      params.require(:thing).permit(:name, :thing_id, :created_at, :updated_at)
    end
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :set_thing, only: [:show, :edit, :update, :destroy]

  # GET /things
  # GET /things.json
  def index
    # @things = Thing.all
  end

  # GET /things/1
  # GET /things/1.json
  def show
  end

  # GET /things/new
  def new
    @thing = Thing.new
  end

  # GET /things/1/edit
  def edit
  end

  # POST /things
  # POST /things.json
  def create
    @thing = Thing.new(thing_params)

    respond_to do |format|
      if @thing.save
        format.html { redirect_to @thing, notice: 'Thing was successfully created.' }
        format.json { render :show, status: :created, location: @thing }
      else
        format.html { render :new }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /things/1
  # PATCH/PUT /things/1.json
  def update
    respond_to do |format|
      if @thing.update(thing_params)
        format.html { redirect_to @thing, notice: 'Thing was successfully updated.' }
        format.json { render :show, status: :ok, location: @thing }
      else
        format.html { render :edit }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    @thing.destroy
    respond_to do |format|
      format.html { redirect_to things_url, notice: 'Thing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @thing = Thing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thing_params
      params.require(:thing).permit(:name, :thing_id, :created_at, :updated_at)
    end
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/things/_form.html.erb
<%= form_with(model: thing, local: true) do |form| %>
  <% if thing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(thing.errors.count, "error") %> prohibited this thing from being saved:</h2>

      <ul>
      <% thing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :thing_id %>
    <%= form.number_field :thing_id %>
  </div>

  <div class="field">
    <%= form.label :created_at %>
    <%= form.datetime_select :created_at %>
  </div>

  <div class="field">
    <%= form.label :updated_at %>
    <%= form.datetime_select :updated_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/things/_index_item.html.erb
<div class="ui card" style="width: 220px;">
  <div class="image">
    <%
      url = thing[:attributes]["image_url"] 
      lurl = (url == nil || url.length == 0) ? "/assets/image-placeholder.png" : url.gsub(/(thumb_)(medium)(\.)/, '\1large\3') 
    %>
    <img src=<%= lurl %>>
  </div>
  <div class="content">
    <div class="description"><%= thing[:attributes]["name"] %> </div>
    <div class="meta" style="display:none"><%= thing[:attributes]["description"] %> </div>
  </div>
  <div class="extra content" style="padding: 10px; margin: 0px;">
    <div class="ui fluid buttons">
      <a target="_blank"
        href=<%= "#{current_env["domains"]["layerkeep"]}/projects/new?source=thingiverse&amp;thing_id=#{thing[:id]}" %>
        class="ui tiny compact primary button layerkeep-manage" role="button">Manage on
        LayerKeep
      </a>
      <a target="_blank" href="<%= "#{current_env["domains"]["thingiverse"]}/thing:#{thing[:id]}" %>" 
        class="ui tiny compact button external-name" role="button"><span>Thingiverse</span></a>
    </div>
  </div>
</div>

app/views/things/_thing_list_item.html.erb
  <%
    url = thing[:attributes]["image_url"] 
    lurl = (url == nil || url.length == 0) ? "/assets/image-placeholder.png" : url.gsub(/(thumb_)(medium)(\.)/, '\1large\3') 
  %>

<div class="column" style="overflow:hidden;cursor: pointer" data-id=<%=thing[:id]%>>
  <div class="ui card">
    <div class="ui blurring image" style="background-image: url('<%= lurl %>'); background-size: cover; background-repeat: no-repeat; background-position: 50% 0;">
    <div class="ui dimmer">
      <div class="card-hover-content">
        <div class="card-hover-content-inner">
          <div style="display:flex; flex: 1;">
              <div class="card-hover-description">
                <p class="card-hover-content-truncate"><%= thing[:attributes]["description"] %></p>
              </div>

              <div class="hover-link">
                <a class="ui icon button" href="#">
                  <i class="large upload icon"></i>
                </a>
              </div>
          </div>
        </div>
      </div>
    </div>

      <img src="<%= lurl %>%" style="opacity: 0">
    </div>

    <div class="content">
      <div class="description hover-name"><%= thing[:attributes]["name"] %> </div>
      <div class="meta" style="display:none"><%= thing[:attributes]["description"] %> </div>
    </div>

  </div>
  
</div>

app/views/things/edit.html.erb
<h1>Editing Thing</h1>

<%= render 'form', thing: @thing %>

<%= link_to 'Show', @thing %> |
<%= link_to 'Back', things_path %>

app/views/things/index.html.erb
<h1 class="title" style="text-align: center; padding-bottom:20px">Search for 3D Models</h1>
<div class="ui fluid container" style="padding-top:20px; overflow: auto; height: 100%; min-height: 100%;">
  <div style="padding: 40px 0px;">
    <div id="results" class="ui fluid container">
      <div class="ui container" style="padding-bottom: 100px;"><br><br>
        <div class="ui centered cards">
          <% @things.each do |thing| %>
            <%= render "things/index_item", thing: thing %>
          <% end %>
        </div>
        <div class="ui centered cards">
          <%= paginate @paginatedthings %>
          
        </div>
        <br><br>
      </div>
    </div>
  </div>
</div>

app/views/things/new.html.erb
<h1>New Thing</h1>

<%= render 'form', thing: @thing %>

<%= link_to 'Back', things_path %>

app/views/things/show.html.erb
<%= react_component("nav/index") %>
<%= react_component("details/index", {item: @thing}) %>

app/views/things/thing_list.html.erb
<div style="margin-bottom: 30px">
  <h4 class="ui header center aligned">
    Manage a project on <a href="https://layerkeep.com" target="_blank" style="color: #016936">LayerKeep</a> or view it on Thingiverse
  </h4>
</div>

<div class="ui three column grid special cards">
  <% @things.each do |thing| %>
    <%= render "things/thing_list_item", thing: thing %>
  <% end %>
</div>

<br><br>

<div class="ui centered cards" style="padding-bottom: 200px">
  <%= paginate @paginatedthings %>          
</div>